### ISSUE TITLE
OAuth does not work sometimes on device

### ISSUE THREAD

**Issue by mops** [fhsjaagshs/FHSTwitterEngine#83]
Tried to use this lib, but OAuth authorization doesn't works. Just opens and closes login view controller.. Pity

**Comment by Ra1G1** [comment]
I'm also facing the same problem, web view just opens and close. I get error code -1012

It was working fine a month back, now it has stopped working.

**Comment by Ra1G1** [comment]
Just checked, working fine on simulator but not on iPad 3 with iOS 8.1.2.

**Comment by dkhamsing** [comment]
Weird, let me check on device

**Comment by dkhamsing** [comment]
@Ra1G1 can you share some code

**Comment by Ra1G1** [comment]
@dkhamsing let me add one more thing to make it more weird, On iPhones everything is working fine but  on iPad it is not and i've used exactly the same code as your demo project ( not even a single change of line, as i have a fear for oAuth :D).

**Comment by dkhamsing** [comment]
Ok.. I will try to find an iPad

**Comment by dkhamsing** [comment]
Just tried on an iPad Air and it was fine :confused:

**Comment by Ra1G1** [comment]
:(

**Comment by dkhamsing** [comment]
Just pinged @fhsjaagshs, maybe he has an idea.

**Comment by AppShackAB** [comment]
I too has this problem. The login is presented and dismissed. Nothing happens

**Comment by dkhamsing** [comment]
Hmm thanks, will check on those devices

**Comment by AppShackAB** [comment]
Id like to add that the example project does work. It's my own implementation that bugs. I'll look into this, could be something wrong with the Twitter app I created at apps.twitter.com. Fyi I'm using Swift.

**Comment by dkhamsing** [comment]
Ah I see. Yeah just tested the demo on device and it's fine. I will try in Swift and see what happens. Please report back if you make any progress.

**Comment by Ra1G1** [comment]
i am using objective C and I'm having same problem in demo project and in my own project.

**Comment by dkhamsing** [comment]
@AppShackAB added a simple swift demo #87

**Comment by IgorBulyga** [comment]
Same problem with Swift demo on iPhone 5S iOS v7.1.

**Comment by dkhamsing** [comment]
Thanks for your report

**Comment by IgorBulyga** [comment]
When we request a token from twitter by URL "https://api.twitter.com/oauth/request_token" with our sign request, twitter return error: NSURLErrorDomain code = -1012. I think something wrong with our sign request method, maybe with some component of oauthHeader string.

**Comment by AppShackAB** [comment]
My problem is solved! I accidentally had the old consumer key =)

**Comment by dkhamsing** [comment]
Cheers

**Comment by IgorBulyga** [comment]
But it did not solve my problem. For the same consumer key authorization works on some device and doesn't work on other.

**Comment by Ra1G1** [comment]
Same with me.. Not solved..

**Comment by dkhamsing** [comment]
Can you report the console error if any

**Comment by IgorBulyga** [comment]
There is no error, only response from twitter, with error code -1012.

**Comment by dkhamsing** [comment]
Please check your twitter app settings

**Comment by IgorBulyga** [comment]
What kind of settings? One project, with same consumer key, secret key runs okay on some devices and login controller appears and after 3 sec disappears on other iPhone.

**Comment by dkhamsing** [comment]
Pretty strange

**Comment by Ra1G1** [comment]
I don't when and how but now it is working fine on the iPad in which I was facing issue.

**Comment by dkhamsing** [comment]
Thanks for your report

**Comment by hkalexling** [comment]
Same here. I am using Xcode 7.2 and iOS 9.2 and have tried on both simulator and iPhone 6s. Both the Swift and ObjC demo show the view controller and close it again without any error printed in the console.

**Comment by hkalexling** [comment]
I changed the consumer key and consumer secret in demo app to the keys of my own twitter app and it's working now
